### ISSUE TITLE
How do I label an axis?

### ISSUE THREAD

**Issue by frasergraham** [wcharczuk/go-chart#10]
None of the examples show labelled axes, and it's not immediately obvious to me how I would do this.

**Comment by wcharczuk** [comment]
the request timings example has a labeled y-axis, https://github.com/wcharczuk/go-chart/blob/master/_examples/request_timings/main.go

if you want to see what it looks like, https://github.com/wcharczuk/go-chart/blob/master/_examples/request_timings/output.png

**Comment by wcharczuk** [comment]
I've added a dedicated example of this in `_examples/axes_labels/main.go`.
