### ISSUE TITLE
How to simulate a realtime, updating graph?

### ISSUE THREAD

**Issue by sprajagopal** [wcharczuk/go-chart#104]
Hi,
I've been playing around with the examples and I couldn't find a realtime (re)rendering example that can update the data in the graph.
Am I missing something or is this not a feature?
Thanks,

**Comment by wcharczuk** [comment]
it's something you'd have to do yourself, the chart itself can be rendered multiple times, you would want to handle how that's done (and how the series are updated) yourself.

i can also add an example

**Comment by wcharczuk** [comment]
I've added an example, it's basically just a tricky way of grabbing a reference to the chart's timeseries, the example can be found in `_examples/rerender`.

Let me know if this is what you were looking for.
