### ISSUE TITLE
Custom Formatter text angle

### ISSUE THREAD

**Issue by frasergraham** [wcharczuk/go-chart#12]
My custom formatter is overlapping the text so I need to either adjust the tick intervals or angle the test. I can see some references in the code to setting text angle but I can't see how it's exposed.

What are my options here.

Also, thanks for being responsive to my other issues :)

**Comment by frasergraham** [comment]
For references, i'm just formatting a duration field...

![screen shot 2016-08-29 at 12 31 10 pm](https://cloud.githubusercontent.com/assets/872362/18064477/7c86fdec-6de4-11e6-8b59-a1ef83c0e28a.png)

**Comment by wcharczuk** [comment]
oh dang, ok, i can make a `TextRotation` property of `chart.Style`, it'll make measuring text kind of gnarly but should be doable.

`TextRotation` is more or less already implemented in the SVG and Raster renderers so it shouldn't be too much of a lift to parameterize other text elements with it.

**Comment by wcharczuk** [comment]
another option, for the moment, is to reduce the number of ticks that are drawn.

generally the tick generator that an axes comes out of the box with will try to keep text from overlapping.

**Comment by wcharczuk** [comment]
sorry this took so long to fix; you can now specify a rotation in degrees.

**Comment by frasergraham** [comment]
Awesome, thankyou.
