### ISSUE TITLE
Invert Y Axis

### ISSUE THREAD

**Issue by AndyNortrup** [wcharczuk/go-chart#15]
As a user I would like to be able to invert a chart axis so that I can show values as having a low absolute value  but a high relative value at the top of the graph.

**Context**
I'm charting rank values with 1 being the highest rank and 100 being a lower relative rank. I would like  to be able to invert the Y axis so that the higher rank shows as being higher on the chart.

**Comment by wcharczuk** [comment]
sounds good, i'll try and work on this this coming weekend

**Comment by AndyNortrup** [comment]
I suppose it could be useful on the XAxis but I'm not sure of a use case that I would personally use that in, but I don't imagine the implementation would be complex enough to justify not doing it.

**Comment by wcharczuk** [comment]
ok, i've added an example `_examples/descending/main.go` which shows how to use the `Descending` property on continuous ranges, let me know if this does what you need it to.

**Comment by AndyNortrup** [comment]
I'll give it a shot over the weekend. Thanks for being responsive on building the feature.

**Comment by AndyNortrup** [comment]
Works Great. Thanks.
<img width="1008" alt="screen shot 2017-01-13 at 7 12 40 pm" src="https://cloud.githubusercontent.com/assets/5915586/21951928/4e02bb9a-d9c4-11e6-93c2-356bbbee89d3.png">
