### ISSUE TITLE
Program stuck while running the following code

### ISSUE THREAD

**Issue by dcu** [wcharczuk/go-chart#19]
```go
package main

import (
	"fmt"
	"os"

	"github.com/wcharczuk/go-chart"
)

func drawChart() {
	sbc := chart.BarChart{
		Height:   512,
		BarWidth: 60,
		XAxis: chart.Style{
			Show: true,
		},
		YAxis: chart.YAxis{
			Style: chart.Style{
				Show: true,
			},
		},
		Bars: []chart.Value{
			{Value: 0, Label: "Blue"},
			{Value: 0, Label: "Green"},
			{Value: 0, Label: "Gray"},
			{Value: 0, Label: "Orange"},
			{Value: 0, Label: "Test"},
			{Value: 0, Label: "??"},
			{Value: 0, Label: "!!"},
		},
	}

	println("rendering")
	err := sbc.Render(chart.PNG, os.Stdout)
	if err != nil {
		fmt.Printf("Error rendering chart: %v\n", err)
	}
}

func main() {
	drawChart()
}
```

**Comment by wcharczuk** [comment]
is there a reason you are setting the values all to zero? the chart is probably having trouble figuring out how to proportion the pie slices. try setting the values to `1`

**Comment by dcu** [comment]
this is just an example to reproduce the issue, my problem is in a program that gets values from an external source and sometimes those values are 0.

It should not fail if the values are 0.

**Comment by wcharczuk** [comment]
i can have the chart remove entries that are zero, but in general what you're describing is effectively bad data and should produce an error

**Comment by wcharczuk** [comment]
i've updated the pie chart to handle zero values, and error if there are no valid values to draw.

**Comment by dcu** [comment]
thanks, can you update the bar chart as well?

**Comment by wcharczuk** [comment]
sure
