### ISSUE TITLE
It's possible to reduce number of labels on X Axis?

### ISSUE THREAD

**Issue by zigazajc007** [wcharczuk/go-chart#197]
It's possible to show less values / labels on X Axis?
It would be great if it could only show minimum, maximum, the middle and maybe 1 or 2 between those.

![stats](https://user-images.githubusercontent.com/44822563/169871521-a0759a5d-8c7c-4ce2-9474-afdc7b7bce07.png)

**Comment by wcharczuk** [comment]
what i've done in this situation is you can rotate the labels on the x axis to make them more legible when they're that constrained, or you can drop the number of ticks you're generating to give them more space.

**Comment by zigazajc007** [comment]
Thanks.

I can't see any example of text rotation for basic chart.

**Comment by zigazajc007** [comment]
Found it: 
```
			Style: chart.Style{
				TextRotationDegrees: 45,
			},
```
