### ISSUE TITLE
More examples please

### ISSUE THREAD

**Issue by jasonmoo** [wcharczuk/go-chart#2]
This is a great lib!  Would love a handful of examples that demonstrate more of the functionality and how to override it.

**Comment by wcharczuk** [comment]
for sure, i'll add something about the parameter overriding to the README.md and add some more concrete examples

**Comment by wcharczuk** [comment]
ok i've added some examples to the `./examples` directory. lemme know if there is something specific you'd want to see.

**Comment by jasonmoo** [comment]
Thanks for the quick response.  Anything on styling non-data elements of the graph?  Specifically around padding the canvas.  Or maybe there's a general styling practice that's applied to everything that I'm not noticing.

**Comment by wcharczuk** [comment]
the logic around the canvas padding is currently kind of incomplete; there is a `Padding` property of the `Style` object but it's not used consistently and i need to clean that up. further, the autofit logic more or less ignores the provided canvas padding. lemme take a pass at trying to figure out why

**Comment by wcharczuk** [comment]
ok, i've tweaked the chart to not blow away user defaults on `chart.Background.Padding`; they should more or less be preserved through `Render()`.

the only other object that is drawn with padding is `Annotation` and even that is kind of on the whims of the style of the outer series.

lmk if this works for you or if you need control over something specific.

**Comment by jasonmoo** [comment]
Very cool man.  Thank you.  

Looks like the background padding pushes the legend entries outside the legend box.  But this issue is completely resolved.   Really appreciate it!

**Comment by wcharczuk** [comment]
Ack, ok fixed the legend issue.

Creating the examples was actually great for finding bugs; it pushed me to test use cases that I haven't been testing up to now.
