### ISSUE TITLE
Change 

### ISSUE THREAD

**Issue by Xeoncross** [wcharczuk/go-chart#20]
There is a default float format (`DefaultFloatFormat` = `%2f`) I would like to change. There doesn't seem to be a good way to do it without recreating the whole `chart.ContinuousSeries` struct so you can change the [`ValueFormatter`](https://github.com/wcharczuk/go-chart/blob/master/value_formatter.go#L40)

**Comment by wcharczuk** [comment]
I've added `XValueFormatter` and `YValueFormatter` fields on the struct, they are coalesced with the default formatter in `GetValueFormatters()`

**Comment by Xeoncross** [comment]
Thank you! That was pretty speedy.

Overall, I'm really enjoying using this library for debugging. Some things are just easier to think about as graphs.

**Comment by wcharczuk** [comment]
glad to hear it!
