### ISSUE TITLE
Panic during init on Windows

### ISSUE THREAD

**Issue by relvacode** [wcharczuk/go-chart#23]
When trying to start a binary on Windows that uses this library the program panics during the init stage.

It looks to be because `go-chart` sets up time zone helpers, except it ignores the error from 

    _eastern, _ = time.LoadLocation("America/New_York")

This casues `_eastern` to be nil.

The error returned here is

    UTC open /usr/local/go\lib\time\zoneinfo.zip: The system cannot find the path specified.

Note this only happens on systems that do not have Go installed because a Go installation contains the required `zoneinfo.zip`. https://golang.org/pkg/time/#LoadLocation.

Is it possible to defer initialisation of time zone helpers until they are actually needed? It seems you cannot rely on accurate time zone information in Go.

**Comment by wcharczuk** [comment]
good catch; annoying that here is a cross platform issue around this, but should be easy to mitigate

**Comment by wcharczuk** [comment]
refactored the helper constants (`NYSEOpen` etc.) to be functions for lazy eval, further we're now using build flags to set up the correct tzi names on windows vs. posix
