### ISSUE TITLE
Can't create a chart of a constant function

### ISSUE THREAD

**Issue by viovanov** [wcharczuk/go-chart#25]
Because of the way `checkRanges` is implemented here: https://github.com/wcharczuk/go-chart/blob/master/chart.go#L274, one can't plot something like `f(x)=3.14`.

**Comment by wcharczuk** [comment]
should be trivial to fix, i forget why i didn't allow 0 variance functions.

**Comment by wcharczuk** [comment]
the caveat here is you have to set at least the range min/max yourself or there has to be another series that does have a > 0 delta

**Comment by viovanov** [comment]
Yeah, I think setting the min/max yourself would be appropriate.
Thanks for the quick reply.

**Comment by wcharczuk** [comment]
ok, do a pull, should be fixed

**Comment by viovanov** [comment]
says i have a `nan y-range delta` now
let me see if i can replicate with a simple example ...

**Comment by viovanov** [comment]
yeah, this fails:

```
	graph := chart.Chart{
		XAxis: chart.XAxis{
			Style: chart.Style{
				Show: true,
			},
		},
		Series: []chart.Series{
			chart.TimeSeries{
				XValues: []time.Time{time.Now(), time.Now().Add(2 * time.Hour)},
				YValues: []float64{3.14, 3.14},
			},
		},
	}
```

**Comment by wcharczuk** [comment]
have to manually specify a range for the yaxis

`YAxis: chart.YAxis { Range: &chart.ContinuousRange { Min: 0, Max: 5 } }` 

etc.

**Comment by viovanov** [comment]
my bad, forgot about that
works, thanks!
