### ISSUE TITLE
Allow creation of XY scatter plots (i.e. disable line between points)

### ISSUE THREAD

**Issue by mattdoran** [wcharczuk/go-chart#26]
I'm experimenting with go-chart to replace some python charting (matplotlib), and I need to produce an XY scatter plot with values against time (see attached as a sample).

When I plot these series using go-chart it draws lines between the points, and I couldn't figure out how to plot points/ticks only.

Is it possible?  Is this something you're considering?   How would you recommend going about this if I were to help implement it? :)

## Sample XY scatter plot
![garbage-collection-durations](https://cloud.githubusercontent.com/assets/577779/23575657/b2a7f208-00e4-11e7-84f8-0d8581d8d133.png)

**Comment by wcharczuk** [comment]
the only real difference between a line plot vs. scatter plot is changing the draw command from line to to move to + circle. 

as far as how this would work from an api perspective, might be necessary to add a "draw mode" property to the series, that would be line vs. point, which would be read by DrawSeries.

lemme take a crack at a prototype this weekend

**Comment by mattdoran** [comment]
Awesome, happy to take a look and give it a try. :)

**Comment by wcharczuk** [comment]
Sure! my advice if you want to give this a bash is to add a couple properties to `Style`, namely `DotWidth` and `DotColor` (the color is kind of optional), and then alter `draw.LineSeries` to draw circles. One caveat, the draw circle function may be a little wonky in the renderers, and may need some love (esp the `RasterRenderer`)

**Comment by wcharczuk** [comment]
took a crack at it here: https://github.com/wcharczuk/go-chart/pull/27

**Comment by wcharczuk** [comment]
going to mark this issue (xy scatter as a feature) closed
