### ISSUE TITLE
Curved ContinuousSeries chart?

### ISSUE THREAD

**Issue by kris-nova** [wcharczuk/go-chart#32]
Is there an easy way or example of a way to fit a best fit curve to a ContinuousSeries chart?

**Comment by wcharczuk** [comment]
Right now there is only a linear regression, is that sufficient? I haven't built polynomial regression yet but that shouldn't be too hard to add.

**Comment by wcharczuk** [comment]
added polynomial regression, you can feed it a degree number to change the function type.
