### ISSUE TITLE
ZValues in chart.ContinuousSeries

### ISSUE THREAD

**Issue by drgrib** [wcharczuk/go-chart#35]
So I was indeed able to use our features from #33 to plot my z values. But it was pretty ugly. I had to index the `z` value from the `x` and `y` `float64` values. The only way I could see to do this was to hash `x` and `y` using `sprintf("%.3f_%.3f", x, y)` and map it to the `z` value:

```
zFirst := zSequence[0]
zMin, zMax := zFirst, zFirst
for _, z := range zSequence[1:] {
	if z < zMin {
		zMin = z
	}
	if z > zMax {
		zMax = z
	}
}

getHash := func(x, y float64) string {
	hash := sprintf("%.3f_%.3f", x, y)
	return hash
}

zHash := map[string]float64{}
for i, x := range xSequence {
	y := ySequence[i]
	z := zSequence[i]
	hash := getHash(x, y)
	zHash[hash] = z
}

viridisOfZ := func(xr, yr chart.Range, x, y float64) drawing.Color {
	hash := getHash(x, y)
	z := zHash[hash]
	return chart.Viridis(z, zMin, zMax)
}
```

I think it would be much better to just add and process an optional `ZValues` in `chart.ContinuousSeries` the same way `XValues` and `YValues` are processed. Then we would need to change `DotColorProvider` to have tho following signature:

```
type DotColorProvider func(xrange, yrange, zrange Range, x, y, z float64) drawing.Color
```

If the `ZValues` are not defined, the runtime can just send this function `0` for `z` and have `zrange` be from `0` to `0`.

With this functionality added, my entire program above could be reduced to

```
viridisOfZ := func(xr, yr, zr chart.Range, x, y, z float64) drawing.Color {
	return chart.Viridis(z, zr.GetMin(), zr.GetMax())
}
```

I think you would have a much easier time implementing this one than I since you know the flow of the plotting section of the package.

**Comment by wcharczuk** [comment]
```zFirst := zSequence[0]
zMin, zMax := zFirst, zFirst
for _, z := range zSequence[1:] {
	if z < zMin {
		zMin = z
	}
	if z > zMax {
		zMax = z
	}
}```

Can be re-written:

`zmin, zmax := chart.Math.MinAndMax(zSequence...)`

The best fix for your use case, as I understand it (you have a 3rd set of values, zSequence, which is the same length as xvalues and yvalues) would be to feed the `GetValue()` index to the color provider.

**Comment by wcharczuk** [comment]
ok this has been updated

**Comment by drgrib** [comment]
@wcharczuk Your solution of sending the `index` would definitely be workable. Are you saying you intended to add this change in #36? I didn't see it there.

**Comment by wcharczuk** [comment]
i've already added the refactor for the provider into master

**Comment by drgrib** [comment]
@wcharczuk Are you sure? It looks like the old signature is still here in `[value_provider.go](https://github.com/wcharczuk/go-chart/blob/master/value_provider.go)`:

```
type DotColorProvider func(xrange, yrange Range, x, y float64) drawing.Color
```

**Comment by wcharczuk** [comment]
sorry forgot to push, check again

**Comment by drgrib** [comment]
Excellent. That fixes the issue for me.
