### ISSUE TITLE
question about functionality

### ISSUE THREAD

**Issue by deltaskelta** [wcharczuk/go-chart#37]
sorry if this is not the proper place, but your website posted on GH profile is down and I didn't see another way to get in touch with you...

I have some very large data sets of accelerometer data (X, Y, Z, Time) that has rows in the 100,000s. With go-chart...is it possible to control the size of the output PNG? if I wanted each data point at a certain space from the previous in order to make a looooong scrolling PNG, is that possible?

**Comment by wcharczuk** [comment]
yep, you can spec a width and height on the chart object itself, the chart will then set the domains for the ranges with that in mind and autofit to that. i can create an example for you if you want

**Comment by deltaskelta** [comment]
@wcharczuk if you have time for an example, that would be great. Thanks!

**Comment by deltaskelta** [comment]
for posterity, the solution is just to set the width of the chart object...

```graph := chart.Chart{
    //chart stuff
    Width: [pixels]
}
```
