### ISSUE TITLE
Stacked graphs

### ISSUE THREAD

**Issue by philevans** [wcharczuk/go-chart#4]
Hi,

I've just been trying this out and I must say I'm very impressed :).  I was just wondering if you were planning to add, or if it would be possible for you to add the ability to do stacked graphs?

**Comment by wcharczuk** [comment]
thanks!

ive been focused primarily on timeseries stuff up to now, with the bulk of the dev for that wrapping up im open to exploring stacked / pie / and any other types of graphs.

if you have an example you like particularly i can start to figure out the best way to integrate them.

**Comment by wcharczuk** [comment]
hey! quick update; if you take a peek at the `v2.0-devel` branch i have a stacked bar chart example in `examples/stacked_bar/main.go`. lmk what you think
