### ISSUE TITLE
StackedBarChart Title 

### ISSUE THREAD

**Issue by iremnurtokac** [wcharczuk/go-chart#43]
Hello,
I am using StackedBarChart and the title overlaps the bars, is there a way to prevent this? Thanks in advance.

**Comment by wcharczuk** [comment]
can you post a screenshot? if you're referring to the chart title, i sometimes add some canvas padding at the top to keep the title from overlapping

**Comment by iremnurtokac** [comment]
This is how it looks like 
png output :
![mychart](https://user-images.githubusercontent.com/9433732/26921419-4546e05e-4c3c-11e7-950c-8c1f733a7837.png)
regarding code piece :
![screenshot from 2017-06-08 11-24-18](https://user-images.githubusercontent.com/9433732/26922255-deebf4e0-4c3e-11e7-85c2-d988be4dd844.png)
Thanks

**Comment by wcharczuk** [comment]
Hey, sorry this took a little while to respond to. I've tweaked the stack bar chart to respect the background padding. See the example in `_examples/stacked_bar/main.go` for how to adjust the padding and draw the title.

**Comment by iremnurtokac** [comment]
Thank you!
