### ISSUE TITLE
go get github.com/wcharczuk/go-chart failed

### ISSUE THREAD

**Issue by hydra13142** [wcharczuk/go-chart#45]
$ go get github.com/wcharczuk/go-chart
# github.com/wcharczuk/go-chart
E:\Code\Go\src\github.com\wcharczuk\go-chart\vector_renderer.go:173: vr.fc.MeasureString(body).Ceil undefined (type fixed.Int26_6 has no field or method Ceil)

intel i7 amd64 win10

**Comment by wcharczuk** [comment]
what version of golang are you using?

**Comment by gdima** [comment]
Golang 1.8.1 on MacOS:
 go get -u github.com/wcharczuk/go-chart


# cd /Users/giuseppe/rete/sorgenti/go_path/src/github.com/golang/freetype; git pull --ff-only
error: refs/heads/master does not point to a valid object!
error: refs/remotes/origin/HEAD does not point to a valid object!
error: refs/remotes/origin/master does not point to a valid object!
error: refs/remotes/origin/wiki does not point to a valid object!
error: refs/tags/release does not point to a valid object!
error: cannot open .git/FETCH_HEAD: Operation timed out
package github.com/golang/freetype/truetype: exit status 1
package github.com/wcharczuk/go-chart/roboto: open /Users/giuseppe/rete/sorgenti/go_path/src/github.com/wcharczuk/go-chart/roboto/roboto.go: operation timed out
package github.com/wcharczuk/go-chart/seq: cannot find package "github.com/wcharczuk/go-chart/seq" in any of:
	/usr/local/go/src/github.com/wcharczuk/go-chart/seq (from $GOROOT)
	/Users/giuseppe/rete/sorgenti/go_path/src/github.com/wcharczuk/go-chart/seq (from $GOPATH)
package github.com/wcharczuk/go-chart/util: cannot find package "github.com/wcharczuk/go-chart/util" in any of:
	/usr/local/go/src/github.com/wcharczuk/go-chart/util (from $GOROOT)
	/Users/giuseppe/rete/sorgenti/go_path/src/github.com/wcharczuk/go-chart/util (from $GOPATH)

**Comment by wcharczuk** [comment]
looks like an issue on github's side
