### ISSUE TITLE
Missing axis bars

### ISSUE THREAD

**Issue by hiendv** [wcharczuk/go-chart#47]
I'm trying [this example](https://github.com/wcharczuk/go-chart/tree/master/_examples/custom_ticks) but the result doesn't contains bars.
Expected:
![image](https://user-images.githubusercontent.com/1917947/28399688-ce9631d0-6d38-11e7-95a0-5b71e63e5604.png)

Result:
![image](https://user-images.githubusercontent.com/1917947/28399644-9b8b95be-6d38-11e7-9506-e9f4c477c254.png)

**Comment by hiendv** [comment]
Re-installation did solve this

**Comment by wcharczuk** [comment]
double checked even though you closed the issue; should be ok now
