### ISSUE TITLE
Time in X Axis

### ISSUE THREAD

**Issue by think-free** [wcharczuk/go-chart#5]
Hi,
I'm using it in a home automation application I'm developing to show historic values  and it works very well, thanks.
I'm wondering if it's possible to show the time (and not only the date) in the x-axis, didn't figure how I can do that ...

**Comment by wcharczuk** [comment]
Set the `ValueFormatter` property on the chart.XAxis, an example can be found in: https://github.com/wcharczuk/go-chart/blob/master/examples/custom_formatters/main.go, there are other pre-built time formatters for you that can be found in: https://github.com/wcharczuk/go-chart/blob/master/value_formatter.go#L22
