### ISSUE TITLE
How easy/hard is it to add new styles of charts?

### ISSUE THREAD

**Issue by fmpwizard** [wcharczuk/go-chart#51]
I'm evaluating using go-chart to replace our server side wkhtmltopdf + d3 setup but one of the chart styles we use a lot is the d3 donut chart

https://bl.ocks.org/mbostock/3887193

Do you have any pointers as to how to add such style of chart?

**Comment by wcharczuk** [comment]
it's not super hard once you know how different drawing primitives work and how other charts have been implemented. for that specific chart you could use the pie chart as a base. the tricky thing there is how to get a curved path as part of other paths that create the full ring.

most of the drawing calls in the drawing library mimic svg, so you could also just see how d3 draws that chart and port the hard parts as well.

hope this helps!

**Comment by fmpwizard** [comment]
Thanks, I'll be looking at this in the coming weeks, if I get it working, I'll post them here for others to use
