### ISSUE TITLE
Incorrect SVG rendering of PieChart when one segment makes up >50% of pie

### ISSUE THREAD

**Issue by lonnc** [wcharczuk/go-chart#56]
I've tried a few different pie charts and and it looks like when one of the segments makes up >50% of the pie that segment is drawn using 360-angle, which in the example below is the orange segment.

This is the png version that I was expecting the svg version to look like:
![screenshot](https://user-images.githubusercontent.com/52671/30898595-ff3309e8-a353-11e7-8f92-4deaacfc93d2.png)

And here is a screenshot of the svg that I got:
![screen shot 2017-09-27 at 07 17 11](https://user-images.githubusercontent.com/52671/30898602-0c4100d6-a354-11e7-9bd4-174474dd09af.png)

Code Snippet:

		palette := summaryPalette{chart.AlternateColorPalette, myOverrideColors}

		pie := chart.PieChart{
			Width:  width,
			Height: height,
			Values: []chart.Value{
				{Value: notAtDepotRemaining.Value, Label: fmt.Sprintf("Remaining %.0f %s", notAtDepotRemaining.Value, notAtDepotRemaining.Unit)},
				{Value: notAtDepotUsed.Value, Label: fmt.Sprintf("Empty %.0f %s", notAtDepotUsed.Value, notAtDepotUsed.Unit)},
				{Value: depotUsed.Value, Label: fmt.Sprintf("Returned %.0f %s", depotUsed.Value, depotUsed.Unit)},
				{Value: depotRemaining.Value, Label: fmt.Sprintf("Stock %.0f %s", depotRemaining.Value, depotRemaining.Unit)},
			},
			ColorPalette: palette,
		}

            ext := path.Ext(r.URL.Path)
		switch ext {
		case ".png":
			w.Header().Set("Content-Type", "image/png")
			if err := pie.Render(chart.PNG, w); err != nil {
				return fmt.Errorf("PNG: %s", err)
			}

		case ".svg":
			w.Header().Set("Content-Type", "image/svg+xml")
			if err := pie.Render(chart.SVG, w); err != nil {
				return fmt.Errorf("SVG: %s", err)
			}

		default:
			http.NotFound(w, r)
		}

**Comment by wcharczuk** [comment]
For my edification, follow up notes; this only affects the SVG rendering of curves > PI in radius.

**Comment by wcharczuk** [comment]
```<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="512" height="512">
<path  d="M 5 5
L 507 5
L 507 507
L 5 507
L 5 5" style="stroke-width:0;stroke:rgba(255,255,255,1.0);fill:rgba(255,255,255,1.0)"/>
<path  d="M 256 256
L 507 256
A 251 251 225.00 0 1 79 79
L 256 256
Z" style="stroke-width:5;stroke:rgba(255,255,255,1.0);fill:rgba(106,195,203,1.0)"/>
<path  d="M 256 256
L 79 79
A 251 251 90.00 0 1 433 79
L 256 256
Z" style="stroke-width:5;stroke:rgba(255,255,255,1.0);fill:rgba(42,190,137,1.0)"/>
<path  d="M 256 256
L 433 79
A 251 251 45.00 0 1 507 256
L 256 256
Z" style="stroke-width:5;stroke:rgba(255,255,255,1.0);fill:rgba(110,128,139,1.0)"/>
</svg>``` reproduces the issue

**Comment by wcharczuk** [comment]
note: have to set the large arc flag on arcs > PI

**Comment by wcharczuk** [comment]
do a pull, should be fixed
