### ISSUE TITLE
package is exist.but is say can't find function

### ISSUE THREAD

**Issue by ChongyuE** [wcharczuk/go-chart#7]
![image](https://cloud.githubusercontent.com/assets/10123859/17284834/bc51efc2-57f0-11e6-944d-e30f67fe3868.png)
package path
/Users/eleven/Desktop/mygo/src/github.com/golang/freetype
font.go also have this struct 
![image](https://cloud.githubusercontent.com/assets/10123859/17284890/4a9a98ce-57f1-11e6-97b3-aa2a4fa3d624.png)
please tell me what probable will cause this problem？thanks

**Comment by wcharczuk** [comment]
did you do `go get -u ./...` yet?

**Comment by ChongyuE** [comment]
i'v tried 。I can run it on windows.but can't run on osx
