### ISSUE TITLE
Adding donut charts

### ISSUE THREAD

**Issue by ligurio** [wcharczuk/go-chart#96]
It would be perfect to add donuts to the range of possible charts types.
Something like this https://datavizcatalogue.com/methods/donut_chart.html

**Comment by kevino83** [comment]
Hello boys,
I created a donut chart adding a circle on the pie-chart and moving externally the legends.

**Comment by wcharczuk** [comment]
yeah you can compose some elements to create this yourself, we can add some recipes for doing it to make it easier though

**Comment by kevino83** [comment]
Hello Will, thanks for the charts.
If it helps I can share my donut version of pie-chart.

**Comment by kevino83** [comment]
Hi Will, sorry for the late. I just committed a super simple version of donut (really a pie clone with some fixed parameters)
