### ISSUE TITLE
example min_max code broken

### ISSUE THREAD

**Issue by rongyi** [wcharczuk/go-chart#99]
_examples/min_max/main.go:14
`YValues: seq.New(seq.NewRandom().WithLen(100).WithAverage(100).WithScale(50)).Array(),`
there is no WithAverage function now
maybe? ==> 
`YValues: seq.New(seq.NewRandom().WithLen(100).WithMax(150).WithMin(40)).Array(),`

**Comment by wcharczuk** [comment]
good catch.
